### ISSUE TITLE
[ServoPi.py] Invalid servo range in the Servo.move method

### ISSUE THREAD

**Issue by sbaron** [abelectronicsuk/ABElectronics_Python_Libraries#11]
In ServoPi.py @ line 255, there's the following condition check:
    if channel >= 0 and channel <= 15:

Which accept the value 0, and fail for value 16.

But the set_pwm() function except a value between 1-16

It should be:
    if channel >= 1 and channel <= 16:

**Comment by abelectronicsuk** [comment]
Thank you for finding the bug.  I have updated the servo class so it should now take channel values between 1 and 16.

**Comment by sbaron** [comment]
Thank you!
