### ISSUE TITLE
Use smbus2 from PyPI

### ISSUE THREAD

**Issue by LukeSkywalker92** [abelectronicsuk/ABElectronics_Python_Libraries#16]
Hey guys,

is there a good reason, why you use the smbus package which needs to be installed via apt?

I tried to run your modules with [smbus2](https://pypi.org/project/smbus2/) which is installable via pip and it works without problems.
The big benefit of using this would be, that you can add it as a dependancy in the setup.py.

If you would like, I could make a pull request for that.

If you prefer keeping the apt-version, I would like to make a fork of your project and publish it on PyPI with the changes if this is ok for you.

Best Luke

**Comment by abelectronicsuk** [comment]
Hello Luke

I have done some performance tests with the smbus2 library and it appears to be about 50% slower than smbus when sending I2C writes to the bus.  As the performance is so much slower we will keep using the smbus library for the moment but you are welcome to fork the project and publish it on PyPi with the changes.
