### ISSUE TITLE
Convert this to python library

### ISSUE THREAD

**Issue by dhhagan** [abelectronicsuk/ABElectronics_Python_Libraries#3]
Would you mind if I converted this to an actual python library for ease-of-use purposes?

**Comment by abelectronicsuk** [comment]
Please go ahead and convert the python code. Will you be posting it online once it is converted?

**Comment by dhhagan** [comment]
Absolutely. It will be located at dhhagan/ADCPi on github. Please let me know how I can properly cite you/give you all the credit! All I'm really doing is restructuring it and adding a setup file!
