### ISSUE TITLE
Whitespace issues in ABE_helpers.py

### ISSUE THREAD

**Issue by Joshua-IRT** [abelectronicsuk/ABElectronics_Python_Libraries#9]
There is a problem with mixed spaces and tabs in ABE_helpers.py in the ADCPi folder.

The lines around the if/elif statement have a single tab mixed in with the spaces, which is causing Python to throw an exception. Can you please fix this?

**Comment by abelectronicsuk** [comment]
Hi

I have fixed the mixed spaces and tabs issue in the ABE_helpers.py files.  It should now work in python without throwing an exception.

**Comment by Joshua-IRT** [comment]
Thank you - problem solved.
